on: push

jobs:
  build-il2cpp-windows:
    runs-on: windows-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: Make output folder
        run: mkdir c:/output

      - name: Make regkeys folder
        run: mkdir c:/regkeys
      
      - name: Get Win 10 SDK Reg Keys
        run: reg export "HKLM\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0" c:/regkeys/winsdk.reg

      - name: Run Docker Image
        run: |
              docker run -it `
              --mount type=bind,source=${{ env.GITHUB_WORKSPACE }}\test-project,target=c:/workspace `
              --mount type=bind,source=c:/regkeys,target=c:/regkeys `
              --mount type=bind,source=c:/output,target=c:/output `
              --mount type=bind,source="C:\Program Files (x86)\Microsoft Visual Studio",target="c:\Program Files (x86)\Microsoft Visual Studio" `
              --mount type=bind,source="C:\Program Files (x86)\Windows Kits",target="C:\Program Files (x86)\Windows Kits" `
              --mount type=bind,source="C:\ProgramData\Microsoft\VisualStudio",target="C:\ProgramData\Microsoft\VisualStudio" `
              --rm `
              --env UNITY_SERIAL=${{ secrets.UNITY_SERIAL }} `
              --env UNITY_USER=${{ secrets.UNITY_USER }} `
              --env UNITY_PASS=${{ secrets.UNITY_PASS }} `
              andrew10001/editor:latest

      - uses: actions/upload-artifact@v2
        with:
          name: IL2CPPWindowsBuild
          path: c:/output/
